/*
 * AquabubblerManager.cpp
 * This code must be generated by the spermatogenesis process
 *  Created on: 7 Oct 2019
 *      Author: arifainchtein
 */

#include <AquabubblerManager.h>

// connect a flow meter to an interrupt pin (see notes on your Arduino model for pin numbers)
FlowMeter Meter0 = FlowMeter(2);
FlowMeter Meter1 = FlowMeter(3);
FlowMeter Meter2 = FlowMeter(2);
FlowMeter Meter3 = FlowMeter(3);
FlowMeter Meter4 = FlowMeter(2);
FlowMeter Meter10 = FlowMeter(3);

AquabubblerManager::AquabubblerManager() {
	// TODO Auto-generated constructor stub

}



AquabubblerManager::begin() {

}

AquabubblerManager::updateValues(){

}
AquabubblerManager::~AquabubblerManager() {
	// TODO Auto-generated destructor stub
}

